services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack edge port
      - "4571:4571"
    environment:
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}  # optional (pro)
      - SERVICES=s3,iam,cloudwatch,logs
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: ./backend
    container_name: local-flask-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - localstack